name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}} 
    - name: Build the Docker image
      run: docker-compose build . --file docker-compose.yml --tag docker-image:$BUILD_NUMBER
    - name: Push docker image docker images to hub
      run: docker --tag docker-image:$BUILD_NUMBER sahith26/server:$BUILD_NUMBER
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
