name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}      
    - name: Build the Docker image Server
      run: docker build . --file /home/runner/work/dockerapp/dockerapp/server/Dockerfile --tag server-image:$BUILD_NUMBER
    - name: Push docker image server to hub
      run: docker tag server-image:$BUILD_NUMBER sahith26/server:$BUILD_NUMBER
    - name: List the docker images
      run: docker images
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker push server image
      run: docker push sahith26/server:$BUILD_NUMBER
