name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build the stack
      run: docker-compose up -f docker-compose.yml
    - name: Test
      run: docker-compose exec -T --network container:nginx appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3050/
