name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build the stack
      run: docker-compose up -d
    - name: Test
      run: docker run --network container:dockerproject-nginx/curl -s --retry 10 --retry-connrefused http://localhost:3050/
